[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pydecisionmaking"
version = "1.0.0"
description = ""

[project.urls]
homepage = "https://github.com/wilsonify/pydecisionmaking"

[tool.setuptools]
packages = ["pydecisionmaking"]